name: CodeCoverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coveralls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: 3.1.301
      - name: Install dependencies
        run: dotnet restore build/Kyameru.Component.Slack.sln
      - name: Build
        run: dotnet build build/Kyameru.Component.Slack.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test tests/UnitTests/Kyameru.Component.Slack.Tests/Kyameru.Component.Slack.Tests.csproj --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=TestCoverage/
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./tests/UnitTests/Kyameru.Component.Slack.Tests/TestCoverage/coverage.info 